### ISSUE TITLE
null refrence exeption 

### ISSUE THREAD

**Issue by momenimohammad23** [pmccolgan/Twitter-API-Simple-Console-Demo#1]
Hi 
can you help me ? 
I get null refrence exeption in this line : 
Console.WriteLine(status.Id > 0 ? "Tweet looks good, id greater than zero: {0}" : "Issue tweeting, returned id:{0}",status.Id);

**Comment by pmccolgan** [comment]
This is running fine for me; for you it looks like the status object hasn't been initialised (is null) and it calls status.Id which throws that exception.

To get that far the service object will have been initialised so there's nothing obvious to me that the application is doing that would cause this (admittedly it could check that objects aren't null before using them but it was supposed to be simple and won't help diagnose this...).

I'd check that the twitter token is set-up correctly and then look at [TweetSharp](https://github.com/danielcrenna/tweetsharp) to see if there's more feedback you could get from the service object or SendTweet method.

**Comment by pmccolgan** [comment]
Haven't heard anything back, going to close this <_<
